# conjoon
# (c) 2007-2017 conjoon.org
# licensing@conjoon.org
#
# conjoon / app-cn_mail
#
# This is the very basic travis configuration for the app-cn_core
# package of the conjoon Open Source Project. It simply creates a
# workspace, adds this package and tries to build it while making sure
# that required packages are merged into the workspace.
language: node_js
env:
  - CN_PACKAGE="app-cn_mail" CN_SENCHA_EXT_VERSION="6.2.0" CN_SENCHA_CMD_VERSION="6.2.2.36" CN_WORKSPACE="/tmp/conjoon"

install:
  - gem install jsduck

before_script:
  - "wget http://cdn.sencha.com/ext/gpl/ext-$CN_SENCHA_EXT_VERSION-gpl.zip"
  - "unzip -q ext-$CN_SENCHA_EXT_VERSION-gpl.zip"
  - "ln -sv `pwd`/ext-$CN_SENCHA_EXT_VERSION $TRAVIS_BUILD_DIR/../ext"

  - "wget http://cdn.sencha.com/cmd/$CN_SENCHA_CMD_VERSION/no-jre/SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "unzip -q SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "chmod +x SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh"
  - "./SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh -q"

  - "export PATH=~/bin/Sencha/Cmd/$CN_SENCHA_CMD_VERSION/:$PATH"

  - "mkdir $CN_WORKSPACE"
  - "sencha -sdk $TRAVIS_BUILD_DIR/../ext generate workspace $CN_WORKSPACE"
  - "mkdir -p $CN_WORKSPACE/packages/local/$CN_PACKAGE"
  - "cp $TRAVIS_BUILD_DIR/. $CN_WORKSPACE/packages/local/$CN_PACKAGE -R"

# add requirements before building
## lib-cn_core
  - "cd /tmp && wget  -O lib-cn_core.zip https://github.com/conjoon/lib-cn_core/archive/master.zip"
  - "unzip lib-cn_core.zip -d $CN_WORKSPACE/packages/local/"
  - "mv $CN_WORKSPACE/packages/local/lib-cn_core-master $CN_WORKSPACE/packages/local/lib-cn_core"
## lib-cn_comp
  - "cd /tmp && wget  -O lib-cn_comp.zip https://github.com/conjoon/lib-cn_comp/archive/master.zip"
  - "unzip lib-cn_comp.zip -d $CN_WORKSPACE/packages/local/"
  - "mv $CN_WORKSPACE/packages/local/lib-cn_comp-master $CN_WORKSPACE/packages/local/lib-cn_comp"


script:
  - "cd $CN_WORKSPACE/packages/local/$CN_PACKAGE && sencha package build"